name: kids_learning
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  flutter_launcher_icons: ^0.9.2
  cupertino_icons: ^1.0.4
  curved_navigation_bar: ^1.0.3
  animated_splash_screen: ^1.3.0
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  flutter:
    sdk: flutter
  awesome_dialog: ^3.2.1
  easy_dialog: ^1.1.1
  google_fonts:
  provider:
  hive:
  hive_flutter:
  path_provider: ^2.0.8
  url_launcher: ^6.1.10
  webview_flutter: ^4.2.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  hive_generator:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/rocket.png"

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
    # - assets/images/
    - assets/images/
    # - assets/grade1testing/1.jpg
    # - assets/audios/
    - assets/audios/
    - assets/images/sensory.png
    # - assets/audios/
    - assets/logo/rocket.png
    - assets/images/card_backside.jpg
    - assets/images/card0.jpg
    - assets/images/card1.jpg
    - assets/images/card2.jpg
    - assets/images/card3.jpg
    - assets/images/card4.jpg
    - assets/images/ear.jpg
    - assets/images/nose.jpg
    - assets/images/eyes.jpg
    - assets/images/reading.png
    - assets/images/welcom.png
    # - assets/audio/.jpg
